name: .NET

env:
  configuration: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dump:
    name: Dump
    runs-on: ubuntu-latest
    permissions:
      actions: none

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$EVENT_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump environment
        run: printenv | sort

  build:

    runs-on: ubuntu-latest

    outputs:
      GitBuildVersionSimple: ${{ steps.gitversion.outputs.GitBuildVersionSimple }}

    env:
      source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # full history

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          7.0.x
        source-url: ${{ env.source-url }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      id: build
      run: dotnet build /bl

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Container
      run: dotnet publish --os linux --arch x64 /t:PublishContainer Verify.Cli

    - name: Publish Linux
      run: dotnet publish -r linux-x64 --self-contained -p:PublishSingleFile=true Verify.Cli

    - name: Publish Windows
      run: dotnet publish -r win-x64 --self-contained -p:PublishSingleFile=true Verify.Cli
      
    # # Set GitBuildVersionSimple output variable
    # - name: gitversion
    #   id: gitversion
    #   run: |
    #     echo "::set-output name=GitBuildVersionSimple::$GitBuildVersionSimple"
    - name: Build logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        # A file, directory or wildcard pattern that describes what to upload
        path: '*.binlog'

    - name: Linux Binary
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64
        path: Verify.Cli/bin/Release/net7.0/linux-x64/publish

    - name: Linux Binary
      uses: actions/upload-artifact@v3
      with:
        name: win-x64
        # A file, directory or wildcard pattern that describes what to upload
        path: Verify.Cli/bin/Release/net7.0/win-x64/publish

  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [build]

    if: github.ref == 'refs/heads/main' # Running this job only for main branch
    steps:
      - uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ needs.build.outputs.GitBuildVersionSimple }}

      - uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

#      - name: Upload assets
#        uses: xresloader/upload-to-github-release@v1
#        with:
#          file: "./nupkg/**/*.nupkg"
#          delete_file: "*.nupkg"
#          overwrite: true
#          release_id: ${{ steps.create_release.outputs.id }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
