name: Rebase
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  rebase:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v3
